parameters:
services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        SunnyFlail\ExchangeRateFetcher\App\Handler\MessageHandlerInterface:
            tags: [messenger.message_handler]

    SunnyFlail\ExchangeRateFetcher\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/**/Enum/'
            - '../src/**/Entity/'
            - '../src/**/Message/'
            - '../src/**/Response/'
            - '../src/Kernel.php'
