parameters:
    nbp_api_url: 'http://api.nbp.pl/api'
services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        SunnyFlail\ExchangeRateFetcher\App\Handler\MessageHandlerInterface:
            tags: [messenger.message_handler]

    SunnyFlail\ExchangeRateFetcher\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/**/Enum/'
            - '../src/**/Entity/'
            - '../src/**/Message/'
            - '../src/**/Response/'
            - '../src/Kernel.php'

    SunnyFlail\ExchangeRateFetcher\NBPApi\Client\ApiClientInterface: '@SunnyFlail\ExchangeRateFetcher\NBPApi\Infrastructure\Symfony\Client\JsonApiClient'

    SunnyFlail\ExchangeRateFetcher\NBPApi\Infrastructure\Symfony\Client\JsonApiClient:
        arguments:
            $baseApiUrl: '%nbp_api_url%'

    SunnyFlail\ExchangeRateFetcher\NBPApi\Sdk\NBPApiSdkInterface: '@SunnyFlail\ExchangeRateFetcher\NBPApi\Sdk\NBPApiSdk'

    SunnyFlail\CurrencyRateFetcher\App\Uuid\UuidGeneratorInterface: '@SunnyFlail\CurrencyRateFetcher\App\Infrastructure\Symfony\Uuid\UuidGenerator'